import "../../app/globals.css";
import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/components/theme-provider";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { getAuthData } from "@/lib/auth";
import BodyBase from "@/components/bodybase";
import Base from "@/components/base";
import ClockClient from "@/components/clockclient";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getAuthData();

  const serverTime = new Date().toISOString();

  return (
    <div className="h-fit">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <SidebarProvider>
          {data?.user ? (
            <>
              <AppSidebar role={data.user.role} />
              <main className="relative w-full overflow-hidden">
                <div className="flex flex-row items-center-safe justify-between">
                  <SidebarTrigger />
                  <ClockClient serverTime={serverTime} />
                </div>

                <Base>
                  <BodyBase>{children}</BodyBase>
                </Base>
              </main>
            </>
          ) : (
            <BodyBase>
              <main>{children}</main>
            </BodyBase>
          )}
        </SidebarProvider>
      </ThemeProvider>
    </div>
  );
}
