import "./globals.css";
import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/components/theme-provider";
import { getAuthData } from "@/lib/auth";
import { AuthProvider } from "@/context/AuthContext";
import Base0 from "@/components/base0";
import NavabarLayout from "@/components/navbar";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getAuthData();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${interTight.variable} ${interTight.className} flex flex-col antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Base0>
            <NavabarLayout />
            <AuthProvider>{children}</AuthProvider>
          </Base0>
        </ThemeProvider>
      </body>
    </html>
  );
}
