// src/app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import { Geist } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { getAuthData } from "@/lib/auth";
import { AuthProvider } from "@/context/AuthContext";
import Base0 from "@/components/base0";
import Navabar from "@/components/navbar";
import ReactQueryProvider from "@/provider/ReactQueryProvider";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

const Geistfallback = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = await getAuthData();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${Geistfallback.className} flex flex-col antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Base0>
            <AuthProvider initialUser={user}>
              <Navabar />
              <ReactQueryProvider>{children}</ReactQueryProvider>
            </AuthProvider>
          </Base0>
        </ThemeProvider>
      </body>
    </html>
  );
}
